name: Build and publish development Docker images
on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  # https://github.com/marketplace/actions/build-and-push-docker-images
  multi-registries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        # https://github.com/docker/setup-buildx-action#inputs
        uses: docker/setup-buildx-action@v1
        with:
          # switch from the default "docker-container" to "docker"
          # because some subsequent steps rely on images built by
          # earlier step(s) and the default driver does not support
          # such a behavior: https://stackoverflow.com/questions/62593004/docker-buildx-cannot-pull-from-local-for-inherited-image
          driver: docker
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.THINK_THEN_RANT_CONTAINER_REGISTRY_TOKEN }}
      
      - name: Docker meta for the YLCBase image 
        # https://github.com/marketplace/actions/docker-meta#keep-up-to-date-with-github-dependabot
        id: docker_meta_ylc_base
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          # list of Docker images to use as base name for tags
          images: thinkthenrant/development-container-base,ghcr.io/thinkthenrant/development-container-base
          tag-sha: true # add git short SHA as Docker tag
      - name: Build and push YLCBase
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./base/Dockerfile
          # platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ylcbase,${{ steps.docker_meta_ylc_base.outputs.tags }}
          labels: ${{ steps.docker_meta_ylc_base.outputs.labels }}
      - name: Inspect
        run: |
          docker images
      - name: Docker meta for the YLCRust image 
        id: docker_meta_ylc_rust
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: thinkthenrant/development-container-rust,ghcr.io/thinkthenrant/development-container-rust
          tag-sha: true
      - name: Build and push YLCRust
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./rust/Dockerfile
          # platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: local,${{ steps.docker_meta_ylc_rust.outputs.tags }}
          labels: ${{ steps.docker_meta_ylc_rust.outputs.labels }}